name: Test Build

on:
  push:
    branches:
      - back-end_drop
      - front-end_drop
      - ci/cd-pipeline-1
      - pipeline-test
      - pipeline2.0
      - front-end
      - back-end
      - dev-ops

  pull_request:
    branches:
      - main
      - back-end_drop
      - front-end_drop
      - front-end
      - back-end
      - dev-ops

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./src/back-end
    - run: npm install
      working-directory: ./src/front-end
    - run: |
        node testingServer.js &
        cd ../front-end
        npm run test --if-present -- localStorage
      working-directory: ./src/back-end
